services:
  db:
    container_name: 'onegramm-db'
    image: postgres:17.5-alpine
    #restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5434:5432'
    networks:
      - custom

networks:
  custom:
    driver: bridge
